apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: order-service
          image: order-service:native
          ports: [{ containerPort: 8080 }]
          readinessProbe:
            httpGet: { path: /q/health/ready, port: 8080 }
